BEGIN;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    email VARCHAR(320) UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS map_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_name VARCHAR(128) NOT NULL UNIQUE,
    map_type VARCHAR(32) NOT NULL,
    level_limit INTEGER NOT NULL DEFAULT 1 CHECK (level_limit >= 1),
    resource_json JSONB NOT NULL DEFAULT '{}'::JSONB
);

CREATE TABLE IF NOT EXISTS players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(64) NOT NULL,
    level INTEGER NOT NULL DEFAULT 1 CHECK (level >= 1),
    exp BIGINT NOT NULL DEFAULT 0 CHECK (exp >= 0),
    hp INTEGER NOT NULL DEFAULT 100 CHECK (hp >= 0),
    attack INTEGER NOT NULL DEFAULT 10 CHECK (attack >= 0),
    defense INTEGER NOT NULL DEFAULT 5 CHECK (defense >= 0),
    gold BIGINT NOT NULL DEFAULT 0 CHECK (gold >= 0),
    current_map BIGINT REFERENCES map_data(id) ON DELETE SET NULL,
    position_x DOUBLE PRECISION NOT NULL DEFAULT 0,
    position_y DOUBLE PRECISION NOT NULL DEFAULT 0,
    UNIQUE (user_id, name)
);

CREATE TABLE IF NOT EXISTS card_spirit_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    race VARCHAR(64) NOT NULL,
    rarity VARCHAR(32) NOT NULL,
    type VARCHAR(32) NOT NULL,
    story TEXT NOT NULL DEFAULT '',
    avatar TEXT,
    base_skill JSONB NOT NULL DEFAULT '{}'::JSONB,
    awakening_skill JSONB NOT NULL DEFAULT '{}'::JSONB
);

CREATE TABLE IF NOT EXISTS player_card_spirits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    spirit_template_id BIGINT NOT NULL REFERENCES card_spirit_templates(id) ON DELETE RESTRICT,
    level INTEGER NOT NULL DEFAULT 1 CHECK (level >= 1),
    affection INTEGER NOT NULL DEFAULT 0 CHECK (affection >= 0),
    exp BIGINT NOT NULL DEFAULT 0 CHECK (exp >= 0),
    awaken_level INTEGER NOT NULL DEFAULT 0 CHECK (awaken_level >= 0),
    acquired_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (player_id, spirit_template_id)
);

CREATE TABLE IF NOT EXISTS card_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    type VARCHAR(32) NOT NULL,
    cost INTEGER NOT NULL DEFAULT 0 CHECK (cost >= 0),
    rarity VARCHAR(32) NOT NULL,
    source_spirit_id BIGINT REFERENCES card_spirit_templates(id) ON DELETE SET NULL,
    effect_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    upgrade_json JSONB NOT NULL DEFAULT '{}'::JSONB
);

CREATE TABLE IF NOT EXISTS player_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    card_template_id BIGINT NOT NULL REFERENCES card_templates(id) ON DELETE RESTRICT,
    level INTEGER NOT NULL DEFAULT 1 CHECK (level >= 1),
    count INTEGER NOT NULL DEFAULT 1 CHECK (count > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (player_id, card_template_id, level)
);

CREATE TABLE IF NOT EXISTS decks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    name VARCHAR(64) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (player_id, name)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_decks_one_active_per_player
    ON decks (player_id) WHERE is_active;

CREATE TABLE IF NOT EXISTS deck_cards (
    deck_id BIGINT NOT NULL REFERENCES decks(id) ON DELETE CASCADE,
    card_id BIGINT NOT NULL REFERENCES player_cards(id) ON DELETE CASCADE,
    amount INTEGER NOT NULL DEFAULT 1 CHECK (amount > 0),
    PRIMARY KEY (deck_id, card_id)
);

CREATE TABLE IF NOT EXISTS affection_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_card_spirit_id BIGINT NOT NULL UNIQUE REFERENCES player_card_spirits(id) ON DELETE CASCADE,
    affection_value INTEGER NOT NULL DEFAULT 0 CHECK (affection_value >= 0),
    interaction_count INTEGER NOT NULL DEFAULT 0 CHECK (interaction_count >= 0),
    last_interaction_time TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS inventories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    item_id BIGINT NOT NULL,
    item_type VARCHAR(32) NOT NULL,
    amount INTEGER NOT NULL DEFAULT 1 CHECK (amount >= 0),
    UNIQUE (player_id, item_id, item_type)
);

CREATE TABLE IF NOT EXISTS npc_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    type VARCHAR(32) NOT NULL,
    story TEXT NOT NULL DEFAULT '',
    battle_deck JSONB NOT NULL DEFAULT '{}'::JSONB,
    reward JSONB NOT NULL DEFAULT '{}'::JSONB,
    is_card_spirit BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS quests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(160) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    type VARCHAR(32) NOT NULL,
    reward_json JSONB NOT NULL DEFAULT '{}'::JSONB
);

CREATE TABLE IF NOT EXISTS player_quests (
    player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    quest_id BIGINT NOT NULL REFERENCES quests(id) ON DELETE CASCADE,
    status VARCHAR(24) NOT NULL DEFAULT 'not_started',
    progress JSONB NOT NULL DEFAULT '{}'::JSONB,
    PRIMARY KEY (player_id, quest_id)
);

CREATE TABLE IF NOT EXISTS battle_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    enemy_id BIGINT NOT NULL,
    result VARCHAR(24) NOT NULL,
    turn_count INTEGER NOT NULL CHECK (turn_count > 0),
    reward_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_players_user_id ON players(user_id);
CREATE INDEX IF NOT EXISTS idx_player_card_spirits_player_id ON player_card_spirits(player_id);
CREATE INDEX IF NOT EXISTS idx_player_cards_player_id ON player_cards(player_id);
CREATE INDEX IF NOT EXISTS idx_decks_player_id ON decks(player_id);
CREATE INDEX IF NOT EXISTS idx_inventories_player_id ON inventories(player_id);
CREATE INDEX IF NOT EXISTS idx_battle_records_player_created_at
    ON battle_records(player_id, created_at DESC);

COMMIT;
