BEGIN;

CREATE TABLE IF NOT EXISTS plant_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    rarity VARCHAR(32) NOT NULL CHECK (rarity IN ('common', 'uncommon', 'rare')),
    base_affection INTEGER NOT NULL CHECK (base_affection BETWEEN 1 AND 4),
    tags JSONB NOT NULL DEFAULT '[]'::JSONB,
    description TEXT NOT NULL DEFAULT '',
    icon TEXT,
    respawn_seconds INTEGER NOT NULL CHECK (respawn_seconds > 0)
);

CREATE TABLE IF NOT EXISTS player_plant_nodes (
    player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    map_id BIGINT NOT NULL REFERENCES map_data(id) ON DELETE CASCADE,
    node_id VARCHAR(64) NOT NULL,
    plant_template_id BIGINT NOT NULL REFERENCES plant_templates(id) ON DELETE RESTRICT,
    available_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (player_id, map_id, node_id)
);

CREATE TABLE IF NOT EXISTS spirit_gift_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spirit_template_id BIGINT NOT NULL REFERENCES card_spirit_templates(id) ON DELETE CASCADE,
    plant_template_id BIGINT REFERENCES plant_templates(id) ON DELETE CASCADE,
    tag VARCHAR(32),
    preference VARCHAR(16) NOT NULL CHECK (preference IN ('favorite', 'liked', 'disliked')),
    dialogue TEXT,
    CHECK ((plant_template_id IS NOT NULL) <> (tag IS NOT NULL))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_spirit_gift_preference_plant
    ON spirit_gift_preferences (spirit_template_id, plant_template_id)
    WHERE plant_template_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_spirit_gift_preference_tag
    ON spirit_gift_preferences (spirit_template_id, tag)
    WHERE tag IS NOT NULL;

CREATE TABLE IF NOT EXISTS spirit_gift_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    player_card_spirit_id BIGINT NOT NULL REFERENCES player_card_spirits(id) ON DELETE CASCADE,
    plant_template_id BIGINT NOT NULL REFERENCES plant_templates(id) ON DELETE RESTRICT,
    affection_gained INTEGER NOT NULL CHECK (affection_gained BETWEEN 1 AND 6),
    gifted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_spirit_gifts_daily
    ON spirit_gift_records (player_card_spirit_id, gifted_at DESC);

INSERT INTO plant_templates (name, rarity, base_affection, tags, description, icon, respawn_seconds)
VALUES
    ('晨露草', 'common', 1, '["清新","草叶"]', '叶尖长时间凝着露珠，是最常见的入门赠礼。', '/assets/generated/sprites/plants/plant-morning-dew-grass-cutout.png', 180),
    ('蜜糖莓', 'common', 1, '["甜味","果实"]', '味道清甜，适合喜欢零食和温暖气味的卡灵。', '/assets/generated/sprites/plants/plant-honey-berry-cutout.png', 240),
    ('阳铃花', 'rare', 4, '["阳光","花朵"]', '花瓣在日照下会发出铃铛般的轻响。', '/assets/generated/sprites/plants/plant-sunbell-flower-cutout.png', 600),
    ('火绒花', 'uncommon', 2, '["温暖","辛香"]', '触感温热，带有淡淡的木炭与香料气息。', '/assets/generated/sprites/plants/plant-firefleece-flower-cutout.png', 420),
    ('风铃藤', 'uncommon', 2, '["花朵","风"]', '细藤随风摇曳时会发出清脆声响。', '/assets/generated/sprites/plants/plant-windbell-vine-cutout.png', 420),
    ('银叶草', 'common', 1, '["清新","月光"]', '银色叶面能映出夜色，是森林中常见的植物。', '/assets/generated/sprites/plants/plant-silverleaf-grass-cutout.png', 240),
    ('星砂薄荷', 'uncommon', 2, '["清凉","草叶"]', '叶片上分布着星点纹理，气味清凉醒神。', '/assets/generated/sprites/plants/plant-star-mint-cutout.png', 420),
    ('月光百合', 'rare', 4, '["月光","花朵"]', '只在幽暗处完全绽放，花心像一轮小小的月亮。', '/assets/generated/sprites/plants/plant-moonlight-lily-cutout.png', 720),
    ('雾绒蕨', 'common', 1, '["安静","草叶"]', '叶缘覆盖柔软白绒，能吸附林间薄雾。', '/assets/generated/sprites/plants/plant-mistfern-cutout.png', 300),
    ('梦露花', 'rare', 4, '["梦境","花朵"]', '花瓣颜色会随观察者的心情产生细微变化。', '/assets/generated/sprites/plants/plant-dreamdew-flower-cutout.png', 900)
ON CONFLICT (name) DO UPDATE SET
    rarity = EXCLUDED.rarity,
    base_affection = EXCLUDED.base_affection,
    tags = EXCLUDED.tags,
    description = EXCLUDED.description,
    icon = EXCLUDED.icon,
    respawn_seconds = EXCLUDED.respawn_seconds;

DELETE FROM spirit_gift_preferences
WHERE spirit_template_id = (SELECT id FROM card_spirit_templates WHERE name = '狼娘·露娜');

INSERT INTO spirit_gift_preferences (spirit_template_id, plant_template_id, tag, preference, dialogue)
VALUES
    ((SELECT id FROM card_spirit_templates WHERE name = '狼娘·露娜'), (SELECT id FROM plant_templates WHERE name = '月光百合'), NULL, 'favorite', '这朵花……有和月光一样安心的味道。'),
    ((SELECT id FROM card_spirit_templates WHERE name = '狼娘·露娜'), NULL, '月光', 'favorite', '月光的气息，我很喜欢。'),
    ((SELECT id FROM card_spirit_templates WHERE name = '狼娘·露娜'), (SELECT id FROM plant_templates WHERE name = '银叶草'), NULL, 'liked', NULL),
    ((SELECT id FROM card_spirit_templates WHERE name = '狼娘·露娜'), (SELECT id FROM plant_templates WHERE name = '星砂薄荷'), NULL, 'liked', NULL),
    ((SELECT id FROM card_spirit_templates WHERE name = '狼娘·露娜'), NULL, '清凉', 'liked', NULL),
    ((SELECT id FROM card_spirit_templates WHERE name = '狼娘·露娜'), (SELECT id FROM plant_templates WHERE name = '火绒花'), NULL, 'disliked', NULL),
    ((SELECT id FROM card_spirit_templates WHERE name = '狼娘·露娜'), NULL, '辛香', 'disliked', NULL);

INSERT INTO player_card_spirits (player_id, spirit_template_id)
SELECT players.id, card_spirit_templates.id
FROM players
CROSS JOIN card_spirit_templates
WHERE card_spirit_templates.name = '狼娘·露娜'
ON CONFLICT (player_id, spirit_template_id) DO NOTHING;

UPDATE map_data
SET resource_json = jsonb_set(
    resource_json,
    '{objects}',
    COALESCE((
        SELECT jsonb_agg(item)
        FROM jsonb_array_elements(COALESCE(resource_json->'objects', '[]'::JSONB)) AS item
        WHERE item->>'type' <> 'collectible_plant'
    ), '[]'::JSONB) || jsonb_build_array(
        jsonb_build_object('type','collectible_plant','node_id','village_dew_01','template_id',(SELECT id FROM plant_templates WHERE name='晨露草'),'x',180,'y',330),
        jsonb_build_object('type','collectible_plant','node_id','village_berry_01','template_id',(SELECT id FROM plant_templates WHERE name='蜜糖莓'),'x',1000,'y',650),
        jsonb_build_object('type','collectible_plant','node_id','village_sunbell_01','template_id',(SELECT id FROM plant_templates WHERE name='阳铃花'),'x',720,'y',360),
        jsonb_build_object('type','collectible_plant','node_id','village_fire_01','template_id',(SELECT id FROM plant_templates WHERE name='火绒花'),'x',390,'y',690),
        jsonb_build_object('type','collectible_plant','node_id','village_vine_01','template_id',(SELECT id FROM plant_templates WHERE name='风铃藤'),'x',1180,'y',910)
    ), TRUE
)
WHERE map_name = '晨曦村';

UPDATE map_data
SET resource_json = jsonb_set(
    resource_json,
    '{objects}',
    COALESCE((
        SELECT jsonb_agg(item)
        FROM jsonb_array_elements(COALESCE(resource_json->'objects', '[]'::JSONB)) AS item
        WHERE item->>'type' <> 'collectible_plant'
    ), '[]'::JSONB) || jsonb_build_array(
        jsonb_build_object('type','collectible_plant','node_id','forest_silver_01','template_id',(SELECT id FROM plant_templates WHERE name='银叶草'),'x',1680,'y',1580),
        jsonb_build_object('type','collectible_plant','node_id','forest_mint_01','template_id',(SELECT id FROM plant_templates WHERE name='星砂薄荷'),'x',1260,'y',1340),
        jsonb_build_object('type','collectible_plant','node_id','forest_lily_01','template_id',(SELECT id FROM plant_templates WHERE name='月光百合'),'x',620,'y',520),
        jsonb_build_object('type','collectible_plant','node_id','forest_fern_01','template_id',(SELECT id FROM plant_templates WHERE name='雾绒蕨'),'x',360,'y',1320),
        jsonb_build_object('type','collectible_plant','node_id','forest_dream_01','template_id',(SELECT id FROM plant_templates WHERE name='梦露花'),'x',980,'y',420)
    ), TRUE
)
WHERE map_name = '微光森林';

COMMIT;
