BEGIN;

CREATE TABLE IF NOT EXISTS npc_ai_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    npc_id BIGINT NOT NULL REFERENCES npc_templates(id) ON DELETE CASCADE,
    summary TEXT NOT NULL DEFAULT '',
    recent_turns JSONB NOT NULL DEFAULT '[]'::JSONB,
    version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1),
    last_interacted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_npc_ai_conversations_player_npc UNIQUE (player_id, npc_id),
    CONSTRAINT ck_npc_ai_conversations_recent_turns_array
        CHECK (jsonb_typeof(recent_turns) = 'array')
);

CREATE INDEX IF NOT EXISTS idx_npc_ai_conversations_retention
    ON npc_ai_conversations (last_interacted_at);

UPDATE npc_templates
SET
    reward = jsonb_set(
        COALESCE(reward, '{}'::JSONB),
        '{ai_profile}',
        jsonb_build_object(
            'dialogue_enabled', true,
            'battle_enabled', COALESCE(reward->'actions', '[]'::JSONB) ? 'battle',
            'persona', CONCAT(name, '。', NULLIF(story, '')),
            'fallback_replies', jsonb_build_array('继续聊聊', '换个话题'),
            'battle_style', '根据当前生命与玩家状态选择稳妥行动'
        ),
        true
    ),
    battle_deck = CASE
        WHEN COALESCE(reward->'actions', '[]'::JSONB) ? 'battle' THEN
            jsonb_set(
                COALESCE(battle_deck, '{}'::JSONB),
                '{guard}',
                to_jsonb(GREATEST(2, COALESCE((battle_deck->>'attack')::INTEGER, 5) / 2)),
                true
            )
        ELSE COALESCE(battle_deck, '{}'::JSONB)
    END;

COMMIT;
