BEGIN;

CREATE TABLE IF NOT EXISTS player_npc_affection (
    player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    npc_id BIGINT NOT NULL REFERENCES npc_templates(id) ON DELETE CASCADE,
    points INTEGER NOT NULL DEFAULT 0 CHECK (points BETWEEN 0 AND 100),
    conversation_count INTEGER NOT NULL DEFAULT 0 CHECK (conversation_count >= 0),
    battle_count INTEGER NOT NULL DEFAULT 0 CHECK (battle_count >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (player_id, npc_id)
);

CREATE TABLE IF NOT EXISTS player_npc_affection_rewards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    npc_id BIGINT NOT NULL REFERENCES npc_templates(id) ON DELETE CASCADE,
    milestone_level INTEGER NOT NULL CHECK (milestone_level BETWEEN 1 AND 5),
    reward_type VARCHAR(24) NOT NULL CHECK (reward_type IN ('card', 'card_spirit')),
    card_template_id BIGINT REFERENCES card_templates(id) ON DELETE RESTRICT,
    spirit_template_id BIGINT REFERENCES card_spirit_templates(id) ON DELETE RESTRICT,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_player_npc_affection_rewards_milestone
        UNIQUE (player_id, npc_id, milestone_level),
    CONSTRAINT ck_player_npc_affection_rewards_payload CHECK (
        (reward_type = 'card' AND card_template_id IS NOT NULL AND spirit_template_id IS NULL)
        OR
        (reward_type = 'card_spirit' AND spirit_template_id IS NOT NULL AND card_template_id IS NULL)
    )
);

CREATE TABLE IF NOT EXISTS npc_gift_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    npc_id BIGINT NOT NULL REFERENCES npc_templates(id) ON DELETE CASCADE,
    plant_template_id BIGINT NOT NULL REFERENCES plant_templates(id) ON DELETE RESTRICT,
    preference VARCHAR(16) NOT NULL
        CHECK (preference IN ('favorite', 'liked', 'neutral', 'disliked')),
    affection_gained INTEGER NOT NULL CHECK (affection_gained BETWEEN 1 AND 6),
    gifted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_npc_gift_records_daily
    ON npc_gift_records (player_id, npc_id, gifted_at DESC);

INSERT INTO card_spirit_templates (
    name, race, rarity, type, story, avatar, base_skill, awakening_skill
)
VALUES
    (
        '晨曦村村长·卡灵', '人族', 'rare', 'support',
        '守望晨曦村多年的村长，将阅历化作守护同伴的力量。',
        '/assets/generated/sprites/npc-village-chief.png',
        '{"name":"晨曦号令","description":"以沉稳判断鼓舞同伴。"}'::JSONB,
        '{"name":"长明守望","description":"村庄的灯火永不熄灭。"}'::JSONB
    ),
    (
        '杂货商·卡灵', '人族', 'uncommon', 'skill',
        '精于观察和取舍的杂货商，总能找到最合适的筹码。',
        '/assets/generated/sprites/npc-shopkeeper.png',
        '{"name":"精明投掷","description":"把不起眼的货物变成制胜机会。"}'::JSONB,
        '{"name":"奇货可居","description":"在关键时刻拿出压箱底的珍藏。"}'::JSONB
    ),
    (
        '铁匠少女苏娜·卡灵', '人族', 'rare', 'physical',
        '苏娜把炉火、锻锤与专注都带进了战场。',
        '/assets/generated/sprites/npc-suna.png',
        '{"name":"炽热锻击","description":"将炉火积蓄在一次精准重击中。"}'::JSONB,
        '{"name":"百炼成锋","description":"千锤百炼后绽放真正锋芒。"}'::JSONB
    ),
    (
        '森林向导·卡灵', '人族', 'rare', 'ranged',
        '熟悉风声与林间路径的向导，从不会在迷雾中失去方向。',
        '/assets/generated/sprites/npc-forest-guide.png',
        '{"name":"引路箭","description":"循着风的轨迹命中目标。"}'::JSONB,
        '{"name":"破雾航标","description":"为同伴指出穿越迷雾的道路。"}'::JSONB
    ),
    (
        '训练教官·卡灵', '人族', 'uncommon', 'physical',
        '严谨克制的实战教官，擅长从细节中捕捉破绽。',
        '/assets/generated/sprites/npc-trainer.png',
        '{"name":"破绽识破","description":"看清对手节奏后果断出击。"}'::JSONB,
        '{"name":"实战本能","description":"将反复训练化为本能判断。"}'::JSONB
    )
ON CONFLICT (name) DO UPDATE SET
    race = EXCLUDED.race,
    rarity = EXCLUDED.rarity,
    type = EXCLUDED.type,
    story = EXCLUDED.story,
    avatar = EXCLUDED.avatar,
    base_skill = EXCLUDED.base_skill,
    awakening_skill = EXCLUDED.awakening_skill;

UPDATE card_templates
SET source_spirit_id = CASE name
    WHEN '晨曦号令' THEN (SELECT id FROM card_spirit_templates WHERE name = '晨曦村村长·卡灵')
    WHEN '精明投掷' THEN (SELECT id FROM card_spirit_templates WHERE name = '杂货商·卡灵')
    WHEN '炽热锻击' THEN (SELECT id FROM card_spirit_templates WHERE name = '铁匠少女苏娜·卡灵')
    WHEN '引路箭' THEN (SELECT id FROM card_spirit_templates WHERE name = '森林向导·卡灵')
    WHEN '破绽识破' THEN (SELECT id FROM card_spirit_templates WHERE name = '训练教官·卡灵')
END
WHERE name IN ('晨曦号令', '精明投掷', '炽热锻击', '引路箭', '破绽识破');

UPDATE npc_templates
SET reward = jsonb_set(
    COALESCE(reward, '{}'::JSONB),
    '{affection_profile}',
    jsonb_build_object(
        'card_spirit_template_id',
            (SELECT id FROM card_spirit_templates WHERE name = '晨曦村村长·卡灵'),
        'favorite_plant_names', jsonb_build_array('阳铃花'),
        'liked_tags', jsonb_build_array('阳光', '花朵'),
        'disliked_tags', jsonb_build_array('辛香'),
        'gift_dialogue', jsonb_build_object(
            'favorite', '阳铃花总让我想起村子初醒的清晨。你有心了。',
            'liked', '明亮又有生机，很适合放在议事桌旁。',
            'neutral', '谢谢你，村里的每一份心意都值得珍惜。',
            'disliked', '味道很有精神，不过我还是更习惯清淡些的香气。'
        )
    ),
    TRUE
)
WHERE name = '晨曦村村长';

UPDATE npc_templates
SET reward = jsonb_set(
    COALESCE(reward, '{}'::JSONB),
    '{affection_profile}',
    jsonb_build_object(
        'card_spirit_template_id',
            (SELECT id FROM card_spirit_templates WHERE name = '杂货商·卡灵'),
        'favorite_plant_names', jsonb_build_array('蜜糖莓'),
        'liked_tags', jsonb_build_array('甜味', '果实'),
        'disliked_tags', jsonb_build_array('月光'),
        'gift_dialogue', jsonb_build_object(
            'favorite', '这批蜜糖莓品相真好。放心，我会留几颗自己尝。',
            'liked', '香甜又实在，这是很会挑东西的人才会选的礼物。',
            'neutral', '收下了。下次也让我看看你的眼光。',
            'disliked', '夜色里的东西不太好估价，不过心意我领了。'
        )
    ),
    TRUE
)
WHERE name = '杂货商';

UPDATE npc_templates
SET reward = jsonb_set(
    COALESCE(reward, '{}'::JSONB),
    '{affection_profile}',
    jsonb_build_object(
        'card_spirit_template_id',
            (SELECT id FROM card_spirit_templates WHERE name = '铁匠少女苏娜·卡灵'),
        'favorite_plant_names', jsonb_build_array('火绒花'),
        'liked_tags', jsonb_build_array('温暖', '辛香'),
        'disliked_tags', jsonb_build_array('清凉'),
        'gift_dialogue', jsonb_build_object(
            'favorite', '火绒花的温度很稳，放在炉边正合适。谢谢。',
            'liked', '这股暖意不错，锻造时闻着会更专心。',
            'neutral', '我收下了。等炉火歇下来，我再仔细看看。',
            'disliked', '太凉了些，靠近炉火可能撑不了多久。心意我明白。'
        )
    ),
    TRUE
)
WHERE name = '铁匠少女苏娜';

UPDATE npc_templates
SET reward = jsonb_set(
    COALESCE(reward, '{}'::JSONB),
    '{affection_profile}',
    jsonb_build_object(
        'card_spirit_template_id',
            (SELECT id FROM card_spirit_templates WHERE name = '森林向导·卡灵'),
        'favorite_plant_names', jsonb_build_array('风铃藤'),
        'liked_tags', jsonb_build_array('风', '清新'),
        'disliked_tags', jsonb_build_array('辛香'),
        'gift_dialogue', jsonb_build_object(
            'favorite', '听见风铃藤的声音，就知道风向没有骗人。',
            'liked', '很清新的气息，带进森林不会惊扰动物。',
            'neutral', '谢谢。我会把它放进随身的标本袋。',
            'disliked', '气味太浓会盖住林中的警讯，不过你的心意我收到了。'
        )
    ),
    TRUE
)
WHERE name = '森林向导';

UPDATE npc_templates
SET reward = jsonb_set(
    COALESCE(reward, '{}'::JSONB),
    '{affection_profile}',
    jsonb_build_object(
        'card_spirit_template_id',
            (SELECT id FROM card_spirit_templates WHERE name = '训练教官·卡灵'),
        'favorite_plant_names', jsonb_build_array('星砂薄荷'),
        'liked_tags', jsonb_build_array('清凉', '草叶'),
        'disliked_tags', jsonb_build_array('梦境'),
        'gift_dialogue', jsonb_build_object(
            'favorite', '星砂薄荷能让人保持清醒。训练前正需要这个。',
            'liked', '气味干净利落，不错。',
            'neutral', '谢谢。礼物收下，训练照常。',
            'disliked', '训练要靠清醒，不靠梦境。不过你的态度值得肯定。'
        )
    ),
    TRUE
)
WHERE name = '训练教官';

INSERT INTO player_npc_affection (
    player_id, npc_id, points, conversation_count, battle_count
)
SELECT player_id, npc_id, 1, 0, 1
FROM npc_first_victory_rewards
ON CONFLICT (player_id, npc_id) DO UPDATE SET
    points = GREATEST(player_npc_affection.points, EXCLUDED.points),
    battle_count = GREATEST(player_npc_affection.battle_count, EXCLUDED.battle_count),
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO player_npc_affection_rewards (
    player_id,
    npc_id,
    milestone_level,
    reward_type,
    card_template_id
)
SELECT player_id, npc_id, 1, 'card', card_template_id
FROM npc_first_victory_rewards
ON CONFLICT (player_id, npc_id, milestone_level) DO NOTHING;

COMMIT;
