BEGIN;

CREATE TABLE IF NOT EXISTS player_card_spirit_fragments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    spirit_template_id BIGINT NOT NULL REFERENCES card_spirit_templates(id) ON DELETE RESTRICT,
    amount INTEGER NOT NULL DEFAULT 0 CHECK (amount >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_player_card_spirit_fragments_player_template
        UNIQUE (player_id, spirit_template_id)
);

CREATE INDEX IF NOT EXISTS idx_player_card_spirit_fragments_player
    ON player_card_spirit_fragments (player_id);

INSERT INTO card_templates (
    name, type, cost, rarity, source_spirit_id, effect_json, upgrade_json
)
VALUES (
    '防御姿态', 'defense', 1, 'common', NULL,
    '{"shield":6}'::JSONB,
    '{}'::JSONB
)
ON CONFLICT (name) DO UPDATE SET
    type = EXCLUDED.type,
    cost = EXCLUDED.cost,
    rarity = EXCLUDED.rarity,
    source_spirit_id = EXCLUDED.source_spirit_id,
    effect_json = EXCLUDED.effect_json,
    upgrade_json = EXCLUDED.upgrade_json;

WITH npc_signatures(npc_name, signature_name) AS (
    VALUES
        ('晨曦村村长', '晨曦号令'),
        ('杂货商', '精明投掷'),
        ('铁匠少女苏娜', '炽热锻击'),
        ('森林向导', '引路箭'),
        ('训练教官', '破绽识破')
), configured AS (
    SELECT
        npc_signatures.npc_name,
        jsonb_build_array(
            jsonb_build_object(
                'card_template_id', (SELECT id FROM card_templates WHERE name = npc_signatures.signature_name),
                'amount', 2
            ),
            jsonb_build_object(
                'card_template_id', (SELECT id FROM card_templates WHERE name = '防御姿态'),
                'amount', 1
            ),
            jsonb_build_object(
                'card_template_id', (SELECT id FROM card_templates WHERE name = '基础攻击'),
                'amount', 3
            )
        ) AS cards
    FROM npc_signatures
)
UPDATE npc_templates
SET battle_deck = COALESCE(npc_templates.battle_deck, '{}'::JSONB) || jsonb_build_object(
    'energy', 3,
    'hand_size', 5,
    'cards', configured.cards
)
FROM configured
WHERE npc_templates.name = configured.npc_name;

INSERT INTO player_card_spirits (player_id, spirit_template_id)
SELECT
    affection.player_id,
    spirit.id
FROM player_npc_affection AS affection
JOIN npc_templates AS npc ON npc.id = affection.npc_id
JOIN card_spirit_templates AS spirit
    ON spirit.id = NULLIF(npc.reward->'affection_profile'->>'card_spirit_template_id', '')::BIGINT
WHERE affection.points >= 80
ON CONFLICT (player_id, spirit_template_id) DO NOTHING;

INSERT INTO player_npc_affection_rewards (
    player_id,
    npc_id,
    milestone_level,
    reward_type,
    spirit_template_id
)
SELECT
    affection.player_id,
    affection.npc_id,
    5,
    'card_spirit',
    spirit.id
FROM player_npc_affection AS affection
JOIN npc_templates AS npc ON npc.id = affection.npc_id
JOIN card_spirit_templates AS spirit
    ON spirit.id = NULLIF(npc.reward->'affection_profile'->>'card_spirit_template_id', '')::BIGINT
WHERE affection.points >= 80
ON CONFLICT (player_id, npc_id, milestone_level) DO NOTHING;

COMMIT;
