BEGIN;

ALTER TABLE players ALTER COLUMN gold SET DEFAULT 300;

CREATE TABLE IF NOT EXISTS item_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    category VARCHAR(32) NOT NULL,
    rarity VARCHAR(32) NOT NULL CHECK (rarity IN ('common', 'uncommon', 'rare')),
    base_affection INTEGER NOT NULL DEFAULT 1 CHECK (base_affection BETWEEN 1 AND 4),
    tags JSONB NOT NULL DEFAULT '[]'::JSONB,
    description TEXT NOT NULL DEFAULT '',
    icon TEXT,
    stack_limit INTEGER NOT NULL DEFAULT 99 CHECK (stack_limit BETWEEN 1 AND 999)
);

CREATE TABLE IF NOT EXISTS npc_shop_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    npc_id BIGINT NOT NULL REFERENCES npc_templates(id) ON DELETE CASCADE,
    item_template_id BIGINT NOT NULL REFERENCES item_templates(id) ON DELETE RESTRICT,
    price INTEGER NOT NULL CHECK (price > 0),
    stock_limit INTEGER NOT NULL DEFAULT 5 CHECK (stock_limit > 0),
    unlock_level INTEGER NOT NULL DEFAULT 1 CHECK (unlock_level BETWEEN 1 AND 5),
    sort_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_npc_shop_item UNIQUE (npc_id, item_template_id)
);

CREATE TABLE IF NOT EXISTS npc_purchase_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    shop_item_id BIGINT NOT NULL REFERENCES npc_shop_items(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price INTEGER NOT NULL CHECK (unit_price > 0),
    purchased_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_npc_purchase_records_daily
    ON npc_purchase_records (player_id, shop_item_id, purchased_at DESC);

ALTER TABLE npc_gift_records
    ALTER COLUMN plant_template_id DROP NOT NULL;
ALTER TABLE npc_gift_records
    ADD COLUMN IF NOT EXISTS item_template_id BIGINT REFERENCES item_templates(id) ON DELETE RESTRICT;
ALTER TABLE npc_gift_records
    DROP CONSTRAINT IF EXISTS ck_npc_gift_records_one_template;
ALTER TABLE npc_gift_records
    ADD CONSTRAINT ck_npc_gift_records_one_template CHECK (
        (plant_template_id IS NOT NULL) <> (item_template_id IS NOT NULL)
    );

ALTER TABLE quests
    ADD COLUMN IF NOT EXISTS issuer_npc_id BIGINT REFERENCES npc_templates(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_quests_issuer_npc ON quests (issuer_npc_id);

INSERT INTO item_templates (
    name, category, rarity, base_affection, tags, description, icon, stack_limit
)
VALUES
    ('香烤肉干', 'food', 'common', 1, '["肉食","冒险","实用"]', '便于携带的咸香肉干，是森林旅行者常备的口粮。', '/assets/generated/icons/gifts/gift-grilled-jerky.png', 99),
    ('蜂蜜烤饼', 'food', 'common', 1, '["甜点","温暖"]', '带着蜂蜜和麦香的烤饼，适合配茶。', '/assets/generated/icons/gifts/gift-honey-flatbread.png', 99),
    ('弹弹果冻', 'food', 'common', 1, '["果冻","甜点"]', '会轻轻晃动的透明果冻，口味每天都不太一样。', '/assets/generated/icons/gifts/gift-bouncy-jelly.png', 99),
    ('晨曦暖茶', 'food', 'common', 1, '["茶饮","温暖","安静"]', '村民招待旅人的日常热饮，味道温和。', '/assets/generated/icons/gifts/gift-dawn-warm-tea.png', 99),
    ('软云抱枕', 'craft', 'common', 1, '["安静","温暖","手工"]', '触感柔软，适合休息，也适合被模仿成不同形状。', '/assets/generated/icons/gifts/gift-soft-cloud-pillow.png', 99),
    ('旅行者地图册', 'book', 'common', 1, '["冒险","知识","实用"]', '标有道路、水源和避雨点的耐用地图册。', '/assets/generated/icons/gifts/gift-traveler-atlas.png', 99),
    ('精工磨刀石', 'craft', 'common', 1, '["锻造","实用","训练"]', '颗粒均匀，适合保养经常使用的工具和武器。', '/assets/generated/icons/gifts/gift-fine-whetstone.png', 99),
    ('透光水晶', 'mineral', 'common', 1, '["矿物","闪亮"]', '内部纯净，迎光时会显出层叠纹理。', '/assets/generated/icons/gifts/gift-translucent-crystal.png', 99)
ON CONFLICT (name) DO UPDATE SET
    category = EXCLUDED.category,
    rarity = EXCLUDED.rarity,
    base_affection = EXCLUDED.base_affection,
    tags = EXCLUDED.tags,
    description = EXCLUDED.description,
    icon = EXCLUDED.icon,
    stack_limit = EXCLUDED.stack_limit;

WITH stock(npc_name, item_name, price, stock_limit, unlock_level, sort_order) AS (
    VALUES
        ('杂货商', '香烤肉干', 20, 5, 1, 10),
        ('杂货商', '蜂蜜烤饼', 20, 5, 1, 20),
        ('杂货商', '弹弹果冻', 20, 5, 1, 30),
        ('杂货商', '晨曦暖茶', 20, 5, 1, 40),
        ('杂货商', '软云抱枕', 35, 3, 1, 50),
        ('杂货商', '旅行者地图册', 40, 3, 3, 60),
        ('铁匠少女苏娜', '精工磨刀石', 30, 5, 1, 10),
        ('铁匠少女苏娜', '透光水晶', 45, 3, 1, 20)
)
INSERT INTO npc_shop_items (npc_id, item_template_id, price, stock_limit, unlock_level, sort_order)
SELECT npc.id, item.id, stock.price, stock.stock_limit, stock.unlock_level, stock.sort_order
FROM stock
JOIN npc_templates AS npc ON npc.name = stock.npc_name
JOIN item_templates AS item ON item.name = stock.item_name
ON CONFLICT (npc_id, item_template_id) DO UPDATE SET
    price = EXCLUDED.price,
    stock_limit = EXCLUDED.stock_limit,
    unlock_level = EXCLUDED.unlock_level,
    sort_order = EXCLUDED.sort_order;

UPDATE npc_templates
SET reward = jsonb_set(
    jsonb_set(COALESCE(reward, '{}'::JSONB), '{actions}', '["dialog","battle","quest"]'::JSONB, TRUE),
    '{service_type}', '"quest"'::JSONB, TRUE
)
WHERE name = '晨曦村村长';

UPDATE npc_templates
SET reward = jsonb_set(
    jsonb_set(COALESCE(reward, '{}'::JSONB), '{actions}', '["dialog","battle","shop"]'::JSONB, TRUE),
    '{service_type}', '"shop"'::JSONB, TRUE
)
WHERE name = '杂货商';

UPDATE npc_templates
SET reward = jsonb_set(
    jsonb_set(COALESCE(reward, '{}'::JSONB), '{actions}', '["dialog","battle","craft"]'::JSONB, TRUE),
    '{service_type}', '"shop"'::JSONB, TRUE
)
WHERE name = '铁匠少女苏娜';

UPDATE npc_templates
SET reward = jsonb_set(
    jsonb_set(COALESCE(reward, '{}'::JSONB), '{actions}', '["dialog","battle","guide"]'::JSONB, TRUE),
    '{service_type}', '"guide"'::JSONB, TRUE
)
WHERE name = '森林向导';

UPDATE npc_templates
SET reward = jsonb_set(
    jsonb_set(COALESCE(reward, '{}'::JSONB), '{actions}', '["dialog","battle","training"]'::JSONB, TRUE),
    '{service_type}', '"training"'::JSONB, TRUE
)
WHERE name = '训练教官';

UPDATE npc_templates SET reward = jsonb_set(
    reward, '{affection_profile,favorite_item_names}', '["商队纪念币","手编守护结"]'::JSONB, TRUE
) WHERE name = '晨曦村村长';
UPDATE npc_templates SET reward = jsonb_set(
    reward, '{affection_profile,favorite_item_names}', '["旅行者地图册"]'::JSONB, TRUE
) WHERE name = '杂货商';
UPDATE npc_templates SET reward = jsonb_set(
    reward, '{affection_profile,favorite_item_names}', '["精工磨刀石"]'::JSONB, TRUE
) WHERE name = '铁匠少女苏娜';
UPDATE npc_templates SET reward = jsonb_set(
    reward, '{affection_profile,favorite_item_names}', '["旅行者地图册"]'::JSONB, TRUE
) WHERE name = '森林向导';
UPDATE npc_templates SET reward = jsonb_set(
    reward, '{affection_profile,favorite_item_names}', '["精工磨刀石"]'::JSONB, TRUE
) WHERE name = '训练教官';

INSERT INTO quests (title, description, type, reward_json, issuer_npc_id)
SELECT seed.title, seed.description, seed.type, seed.reward_json, npc.id
FROM npc_templates AS npc
CROSS JOIN (VALUES
    ('村道补给', '为准备进入森林的旅人检查补给，并带回一份晨曦暖茶。', 'delivery', '{"gold":120,"objective":"own_item","item_name":"晨曦暖茶","amount":1}'::JSONB),
    ('林缘踏查', '前往村庄东缘观察植物与道路，记录一次采集。', 'exploration', '{"gold":160,"objective":"collect_plant","amount":1}'::JSONB),
    ('实战准备', '完成一次训练教官的实战切磋。', 'battle', '{"gold":200,"objective":"battle_npc","npc_name":"训练教官","amount":1}'::JSONB)
) AS seed(title, description, type, reward_json)
WHERE npc.name = '晨曦村村长'
  AND NOT EXISTS (SELECT 1 FROM quests WHERE quests.title = seed.title);

COMMIT;
