BEGIN;

CREATE TABLE IF NOT EXISTS player_story_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    story_key VARCHAR(64) NOT NULL,
    stage VARCHAR(32) NOT NULL DEFAULT 'arrival',
    data_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_player_story_progress_player_story UNIQUE (player_id, story_key),
    CONSTRAINT ck_player_story_progress_stage CHECK (
        stage IN ('arrival', 'prepare', 'forest_signal', 'return_village', 'complete')
    )
);

CREATE INDEX IF NOT EXISTS idx_player_story_progress_player
    ON player_story_progress (player_id);

INSERT INTO npc_templates (name, type, story, battle_deck, reward, is_card_spirit)
VALUES (
    '狼娘·露娜',
    'story_boss',
    '追查微光森林异常月痕的狼族少女。她把带有同样共鸣的旅人误认为雾袭者。',
    jsonb_build_object(
        'hp', 36,
        'energy', 3,
        'hand_size', 5,
        'monster_rank', 'boss',
        'spirit_template_id', (SELECT id FROM card_spirit_templates WHERE name = '狼娘·露娜'),
        'cards', jsonb_build_array(
            jsonb_build_object(
                'card_template_id', (SELECT id FROM card_templates WHERE name = '月牙撕裂'),
                'amount', 2
            ),
            jsonb_build_object(
                'card_template_id', (SELECT id FROM card_templates WHERE name = '防御姿态'),
                'amount', 2
            ),
            jsonb_build_object(
                'card_template_id', (SELECT id FROM card_templates WHERE name = '基础攻击'),
                'amount', 3
            )
        )
    ),
    jsonb_build_object(
        'actions', jsonb_build_array('dialog', 'battle'),
        'sprite', 'npc-luna',
        'portrait', '/assets/generated/portraits/luna.webp',
        'story_gate', 'opening_moon_scar',
        'dialogue', jsonb_build_array(
            '你身上有那道月痕的味道。别再往前。',
            '我在追一个没有气味、只留下月痕的人。它让幼狼对着空地发抖。',
            '你说自己也在调查？那就证明你不是在追自己的脚印。'
        )
    ),
    FALSE
)
ON CONFLICT (name) DO UPDATE SET
    type = EXCLUDED.type,
    story = EXCLUDED.story,
    battle_deck = EXCLUDED.battle_deck,
    reward = EXCLUDED.reward,
    is_card_spirit = EXCLUDED.is_card_spirit;

UPDATE map_data
SET resource_json = jsonb_set(
    resource_json,
    '{objects}',
    COALESCE(
        (
            SELECT jsonb_agg(item)
            FROM jsonb_array_elements(COALESCE(resource_json->'objects', '[]'::JSONB)) AS item
            WHERE NOT (
                item->>'type' = 'npc'
                AND item->>'template_name' = '狼娘·露娜'
            )
        ),
        '[]'::JSONB
    ) || jsonb_build_array(
        jsonb_build_object(
            'type', 'npc',
            'template_id', (SELECT id FROM npc_templates WHERE name = '狼娘·露娜'),
            'template_name', '狼娘·露娜',
            'sprite', 'npc-luna',
            'story_gate', 'opening_moon_scar',
            'story_stage', 'forest_signal',
            'x', 620,
            'y', 520
        )
    ),
    TRUE
)
WHERE map_name = '微光森林';

COMMIT;
